sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客的仓库地址
env:
  global:
    # Github Pages
    - GH_REF: github.com/zhangbiao-code/zhangbiao-code.github.io.git
    # Coding Pages
    - CO_REF: e.coding.net/zhangbiao-code/blog/zhangbiao-blog.git
    # Gitee Pages
    - GITEE_REF: gitee.com/zhang-biao/zhang-biao.gitee.io.git

# 指定博客分支
branches:
  only:
    - blog-source # build master branch only

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install


# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo g

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - cd ./public
  - git init
  - git config user.name "zhangbiao-code"
  - git config user.email "2213733404@qq.com"
  - git add .
  - git commit -m "TravisCI 自动部署"

  # Github Pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  # Coding Pages
  - git push --force --quiet "https://OWXQIBpQlE:${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" master:master --tags
  # Coding Pages
  - git push --quiet "https://OWXQIBpQlE:${CO_TOKEN}@${CO_REF}" master:master --tags
  # Gitee Pages
  - git push --force --quiet "https://${GITEE_TOKEN}@${GITEE_REF}" master:master
  # Gitee Pages
  - git push --quiet "https://${GITEE_TOKEN}@${GITEE_REF}" master:master --tags

# End: Build LifeCycle
